"""Describe your changes

Revision ID: 14b92f62d489
Revises: 1a6923c64509
Create Date: 2025-10-29 19:36:59.668356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14b92f62d489'
down_revision: Union[str, Sequence[str], None] = '1a6923c64509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('time_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_employee_workdate')
    )
    op.create_table('leaves',
    sa.Column('leave_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('leave_id'),
    sa.UniqueConstraint('employee_id', 'start_date', 'end_date', name='uq_employee_leave_dates')
    )
    op.drop_table('audit_logs')
    op.drop_table('leave')
    op.drop_table('attendance')
    op.drop_constraint(op.f('departments_organisation_id_name_key'), 'departments', type_='unique')
    op.create_unique_constraint('ux_departments_org_name', 'departments', ['organisation_id', 'name'])
    op.drop_constraint(op.f('designations_organisation_id_title_key'), 'designations', type_='unique')
    op.create_unique_constraint('ux_designations_org_title', 'designations', ['organisation_id', 'title'])
    op.add_column('employees', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('work_email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('mobile_phone', sa.String(length=30), nullable=True))
    op.add_column('employees', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('fathers_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('annual_ctc', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('pay_frequency', sa.String(length=20), server_default=sa.text("'Monthly'"), nullable=True))
    op.add_column('employees', sa.Column('uan_link_status', sa.String(length=50), server_default=sa.text("'Unlinked'"), nullable=True))
    op.drop_constraint(op.f('ux_payperiods_org_dates'), 'pay_periods', type_='unique')
    op.create_unique_constraint('ux_pay_periods_org_dates', 'pay_periods', ['organisation_id', 'start_date', 'end_date'])
    op.add_column('roles', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('statutory_settings', 'employer_contribution',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('statutory_settings', 'employee_contribution',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.drop_constraint(op.f('work_locations_organisation_id_name_key'), 'work_locations', type_='unique')
    op.create_unique_constraint('ux_worklocations_org_name', 'work_locations', ['organisation_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_worklocations_org_name', 'work_locations', type_='unique')
    op.create_unique_constraint(op.f('work_locations_organisation_id_name_key'), 'work_locations', ['organisation_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('statutory_settings', 'employee_contribution',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('statutory_settings', 'employer_contribution',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.drop_column('roles', 'updated_at')
    op.drop_constraint('ux_pay_periods_org_dates', 'pay_periods', type_='unique')
    op.create_unique_constraint(op.f('ux_payperiods_org_dates'), 'pay_periods', ['organisation_id', 'start_date', 'end_date'], postgresql_nulls_not_distinct=False)
    op.drop_column('employees', 'uan_link_status')
    op.drop_column('employees', 'pay_frequency')
    op.drop_column('employees', 'annual_ctc')
    op.drop_column('employees', 'fathers_name')
    op.drop_column('employees', 'marital_status')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'mobile_phone')
    op.drop_column('employees', 'work_email')
    op.drop_column('employees', 'middle_name')
    op.drop_constraint('ux_designations_org_title', 'designations', type_='unique')
    op.create_unique_constraint(op.f('designations_organisation_id_title_key'), 'designations', ['organisation_id', 'title'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('ux_departments_org_name', 'departments', type_='unique')
    op.create_unique_constraint(op.f('departments_organisation_id_name_key'), 'departments', ['organisation_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_table('attendance',
    sa.Column('attendance_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attendance_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('check_out', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('salary_assignment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('attendance_employee_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_assignment_id'], ['employee_salary_assignments.salary_assignment_id'], name=op.f('attendance_salary_assignment_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('attendance_id', name=op.f('attendance_pkey'))
    )
    op.create_table('leave',
    sa.Column('leave_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('leave_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('approved_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], name=op.f('leave_approved_by_fkey')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('leave_employee_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('leave_id', name=op.f('leave_pkey'))
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('entity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('log_id', name=op.f('audit_logs_pkey'))
    )
    op.drop_table('leaves')
    op.drop_table('attendances')
    # ### end Alembic commands ###
