"""Describe your chang

Revision ID: 81eee9f8ac2b
Revises: 1de5e6258abe
Create Date: 2025-10-29 20:38:48.219510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81eee9f8ac2b'
down_revision: Union[str, Sequence[str], None] = '1de5e6258abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_statutory_details',
    sa.Column('stat_detail_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('uan_number', sa.String(length=20), nullable=True),
    sa.Column('esi_number', sa.String(length=20), nullable=True),
    sa.Column('pt_location', sa.String(length=100), nullable=True),
    sa.Column('tax_regime', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.String(length=5), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stat_detail_id'),
    sa.UniqueConstraint('employee_id', 'effective_from', name='ux_employee_stat_effective_from'),
    sa.UniqueConstraint('pan_number')
    )
    op.create_table('payroll_tax_summaries',
    sa.Column('tax_summary_id', sa.UUID(), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('employee_pf', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('employer_pf', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('employer_esi', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('employee_esi', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_summary_id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name='ux_payroll_run_employee')
    )
    op.create_table('tax_declarations',
    sa.Column('declaration_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('declared_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('declaration_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_declarations')
    op.drop_table('payroll_tax_summaries')
    op.drop_table('employee_statutory_details')
    # ### end Alembic commands ###
