"""baseline

Revision ID: 84893e373797
Revises: 81eee9f8ac2b
Create Date: 2025-10-29 21:35:19.791921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84893e373797'
down_revision: Union[str, Sequence[str], None] = '81eee9f8ac2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_file_formats',
    sa.Column('format_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('bank_code', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('branch_code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('file_type', postgresql.ENUM('CSV', 'TXT', 'XML', name='bank_file_type_t'), nullable=False),
    sa.Column('header_line', sa.Text(), nullable=True),
    sa.Column('data_line_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('format_id'),
    sa.UniqueConstraint('organisation_id', 'bank_code', 'name', name='uq_bank_format')
    )
    op.create_table('loan_types',
    sa.Column('loan_type_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_installments', sa.SmallInteger(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('is_interest_applicable', sa.Boolean(), nullable=False),
    sa.Column('is_salary_advance', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('loan_type_id'),
    sa.UniqueConstraint('organisation_id', 'name', name='uq_loan_type_org_name')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('payment_batches',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('format_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('upload_path', sa.Text(), nullable=True),
    sa.Column('total_employees', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', postgresql.ENUM('Generated', 'Uploaded', 'Rejected', 'Paid', name='payment_status_t'), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_ref', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['format_id'], ['bank_file_formats.format_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('batch_id'),
    sa.UniqueConstraint('payroll_run_id', 'format_id', name='uq_payment_batch_run_format')
    )
    op.create_table('employee_bank_details',
    sa.Column('bank_detail_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bank_detail_id'),
    sa.UniqueConstraint('employee_id', 'effective_from', name='uq_bank_employee_from')
    )
    op.create_table('employee_loans',
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('loan_type_id', sa.UUID(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('installment_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_installments', sa.SmallInteger(), nullable=False),
    sa.Column('installments_paid', sa.SmallInteger(), nullable=True),
    sa.Column('start_month', sa.Date(), nullable=False),
    sa.Column('end_month', sa.Date(), nullable=True),
    sa.Column('status', postgresql.ENUM('Pending', 'Active', 'Completed', 'Cancelled', 'Rejected', name='loan_status_t'), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.loan_type_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('loan_id'),
    sa.UniqueConstraint('employee_id', 'loan_type_id', 'start_month', name='uq_loan_employee_type_month')
    )
    op.create_table('loan_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('loan_type_id', sa.UUID(), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('requested_installments', sa.SmallInteger(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.loan_type_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.organisation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('loan_installments',
    sa.Column('installment_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('installment_no', sa.SmallInteger(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_component', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('principal_component', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['employee_loans.loan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('installment_id'),
    sa.UniqueConstraint('loan_id', 'installment_no', name='uq_loan_installment_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_installments')
    op.drop_table('loan_requests')
    op.drop_table('employee_loans')
    op.drop_table('employee_bank_details')
    op.drop_table('payment_batches')
    op.drop_table('audit_logs')
    op.drop_table('loan_types')
    op.drop_table('bank_file_formats')
    # ### end Alembic commands ###
